# Generated by Django 3.2.2 on 2021-06-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color', to='base.product')),
            ],
        ),
    ]
